### ISSUE TITLE
v0.5-pre2 - The Epic Re-Write

### ISSUE THREAD

**Issue by IridescentRose** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#55]
- [x] 100% ME Usage
- [x] Enforce options settings
- [x] Profiling & RAM Optimizations
- [x] Partial Stardust Integration?
